/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PinSettings = IDL.Record({
  'parentalPIN' : IDL.Text,
  'userPIN' : IDL.Text,
});
export const CreateUserInput = IDL.Record({
  'username' : IDL.Text,
  'pinSettings' : PinSettings,
  'password' : IDL.Text,
  'email' : IDL.Text,
});
export const AppLockState = IDL.Record({ 'isLocked' : IDL.Bool });
export const AppLocks = IDL.Record({
  'tiktok' : AppLockState,
  'instagram' : AppLockState,
  'facebook' : AppLockState,
  'youtube' : AppLockState,
});
export const UserSettings = IDL.Record({
  'userRole' : UserRole,
  'pinSettings' : PinSettings,
  'sharedWith' : IDL.Vec(IDL.Principal),
  'appLocks' : AppLocks,
});
export const ProfileView = IDL.Record({
  'username' : IDL.Text,
  'email' : IDL.Text,
  'settings' : IDL.Opt(UserSettings),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CreateVideoMetaInput = IDL.Record({
  'title' : IDL.Text,
  'blob' : ExternalBlob,
});
export const VideoMeta = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'blob' : ExternalBlob,
  'timestamp' : IDL.Int,
  'uploader' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'email' : IDL.Text,
  'settings' : UserSettings,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createUser' : IDL.Func([CreateUserInput], [ProfileView], []),
  'createVideoMeta' : IDL.Func([CreateVideoMetaInput], [IDL.Text], []),
  'deleteVideoMeta' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllVideos' : IDL.Func([], [IDL.Vec(VideoMeta)], ['query']),
  'getCallerProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMySubscriptions' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getSubscriberCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isSubscribed' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isUserExists' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'saveAppLock' : IDL.Func([IDL.Principal, AppLocks], [], []),
  'saveBasicSettings' : IDL.Func([IDL.Principal, UserSettings], [], []),
  'subscribe' : IDL.Func([IDL.Principal], [], []),
  'unsubscribe' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PinSettings = IDL.Record({
    'parentalPIN' : IDL.Text,
    'userPIN' : IDL.Text,
  });
  const CreateUserInput = IDL.Record({
    'username' : IDL.Text,
    'pinSettings' : PinSettings,
    'password' : IDL.Text,
    'email' : IDL.Text,
  });
  const AppLockState = IDL.Record({ 'isLocked' : IDL.Bool });
  const AppLocks = IDL.Record({
    'tiktok' : AppLockState,
    'instagram' : AppLockState,
    'facebook' : AppLockState,
    'youtube' : AppLockState,
  });
  const UserSettings = IDL.Record({
    'userRole' : UserRole,
    'pinSettings' : PinSettings,
    'sharedWith' : IDL.Vec(IDL.Principal),
    'appLocks' : AppLocks,
  });
  const ProfileView = IDL.Record({
    'username' : IDL.Text,
    'email' : IDL.Text,
    'settings' : IDL.Opt(UserSettings),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CreateVideoMetaInput = IDL.Record({
    'title' : IDL.Text,
    'blob' : ExternalBlob,
  });
  const VideoMeta = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'blob' : ExternalBlob,
    'timestamp' : IDL.Int,
    'uploader' : IDL.Principal,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'email' : IDL.Text,
    'settings' : UserSettings,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createUser' : IDL.Func([CreateUserInput], [ProfileView], []),
    'createVideoMeta' : IDL.Func([CreateVideoMetaInput], [IDL.Text], []),
    'deleteVideoMeta' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllVideos' : IDL.Func([], [IDL.Vec(VideoMeta)], ['query']),
    'getCallerProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMySubscriptions' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getSubscriberCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isSubscribed' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isUserExists' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'saveAppLock' : IDL.Func([IDL.Principal, AppLocks], [], []),
    'saveBasicSettings' : IDL.Func([IDL.Principal, UserSettings], [], []),
    'subscribe' : IDL.Func([IDL.Principal], [], []),
    'unsubscribe' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };